export type TemplateCategory = 'general' | 'academic' | 'personal' | 'presentation'

export interface TemplateCategoryInfo {
  id: TemplateCategory
  label: string
}

export const TEMPLATE_CATEGORIES: TemplateCategoryInfo[] = [
  { id: 'general', label: 'General' },
  { id: 'academic', label: 'Academic' },
  { id: 'personal', label: 'Personal' },
  { id: 'presentation', label: 'Presentation' },
]

export interface ProjectTemplate {
  id: string
  name: string
  description: string
  category: TemplateCategory
  /** Path under /public rendered from the template's own first PDF page — not a mockup. */
  previewImage: string
  mainTexContent: string
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'blank-article',
    name: 'Blank Article',
    description: 'A minimal article with a title and one empty section.',
    category: 'general',
    previewImage: '/templates/blank-article.png',
    mainTexContent: [
      '\\documentclass{article}',
      '\\usepackage[utf8]{inputenc}',
      '',
      '\\title{Untitled}',
      '\\author{}',
      '\\date{}',
      '',
      '\\begin{document}',
      '',
      '\\maketitle',
      '',
      '\\section{Introduction}',
      '',
      '\\end{document}',
      '',
    ].join('\n'),
  },
  {
    id: 'two-column-paper',
    name: 'Two-Column Paper',
    description: 'Conference-style two-column layout with an abstract.',
    category: 'general',
    previewImage: '/templates/two-column-paper.png',
    mainTexContent: [
      '\\documentclass[10pt,twocolumn]{article}',
      '\\usepackage[utf8]{inputenc}',
      '\\usepackage{lipsum}',
      '',
      '\\title{Paper Title}',
      '\\author{Author Name \\\\ Affiliation}',
      '\\date{}',
      '',
      '\\begin{document}',
      '',
      '\\maketitle',
      '',
      '\\begin{abstract}',
      '\\lipsum[1]',
      '\\end{abstract}',
      '',
      '\\section{Introduction}',
      '\\lipsum[2]',
      '',
      '\\section{Related Work}',
      '\\lipsum[3]',
      '',
      '\\section{Conclusion}',
      '',
      '\\end{document}',
      '',
    ].join('\n'),
  },
  {
    id: 'simple-report',
    name: 'Simple Report',
    description: 'A report with a table of contents and a few starter sections.',
    category: 'academic',
    previewImage: '/templates/simple-report.png',
    mainTexContent: [
      '\\documentclass{report}',
      '\\usepackage[utf8]{inputenc}',
      '',
      '\\title{Untitled Report}',
      '\\author{}',
      '\\date{}',
      '',
      '\\begin{document}',
      '',
      '\\maketitle',
      '\\tableofcontents',
      '',
      '\\chapter{Introduction}',
      '',
      '\\chapter{Methodology}',
      '',
      '\\chapter{Conclusion}',
      '',
      '\\end{document}',
      '',
    ].join('\n'),
  },
  {
    id: 'thesis-chapter',
    name: 'Thesis',
    description: 'Book-style thesis with title page, TOC, chapters, and a bibliography.',
    category: 'academic',
    previewImage: '/templates/thesis-chapter.png',
    mainTexContent: [
      '\\documentclass[12pt]{report}',
      '\\usepackage[utf8]{inputenc}',
      '',
      '\\title{Thesis Title}',
      '\\author{Your Name}',
      '\\date{\\today}',
      '',
      '\\begin{document}',
      '',
      '\\maketitle',
      '\\tableofcontents',
      '',
      '\\chapter{Introduction}',
      'Motivation and research questions go here.',
      '',
      '\\chapter{Literature Review}',
      '',
      '\\chapter{Methodology}',
      '',
      '\\chapter{Results}',
      '',
      '\\chapter{Conclusion}',
      '',
      '\\begin{thebibliography}{9}',
      '\\bibitem{example} A. Author, \\textit{Title of the Work}, Publisher, Year.',
      '\\end{thebibliography}',
      '',
      '\\end{document}',
      '',
    ].join('\n'),
  },
  {
    id: 'math-homework',
    name: 'Math Homework',
    description: 'Numbered problem set with amsmath for equations.',
    category: 'academic',
    previewImage: '/templates/math-homework.png',
    mainTexContent: [
      '\\documentclass{article}',
      '\\usepackage[utf8]{inputenc}',
      '\\usepackage{amsmath, amssymb}',
      '',
      '\\title{Homework Set}',
      '\\author{Your Name}',
      '\\date{\\today}',
      '',
      '\\begin{document}',
      '',
      '\\maketitle',
      '',
      '\\begin{enumerate}',
      '  \\item Solve for $x$:',
      '  \\[ 2x + 3 = 11 \\]',
      '',
      '  \\item Prove that $\\sqrt{2}$ is irrational.',
      '',
      '  \\item Evaluate the integral:',
      '  \\[ \\int_0^1 x^2 \\, dx \\]',
      '\\end{enumerate}',
      '',
      '\\end{document}',
      '',
    ].join('\n'),
  },
  {
    id: 'cv-resume',
    name: 'CV / Resume',
    description: 'Clean single-column resume with experience and education sections.',
    category: 'personal',
    previewImage: '/templates/cv-resume.png',
    mainTexContent: [
      '\\documentclass[11pt]{article}',
      '\\usepackage[utf8]{inputenc}',
      '\\usepackage[margin=1in]{geometry}',
      '\\usepackage{titlesec}',
      '\\usepackage{enumitem}',
      '\\titleformat{\\section}{\\large\\bfseries}{}{0em}{}[\\titlerule]',
      '\\pagestyle{empty}',
      '',
      '\\begin{document}',
      '',
      '\\begin{center}',
      '  {\\Huge Your Name} \\\\[4pt]',
      '  email@example.com \\quad | \\quad +1 (555) 123-4567 \\quad | \\quad City, Country',
      '\\end{center}',
      '',
      '\\section{Experience}',
      '\\textbf{Job Title} \\hfill Company Name \\\\',
      '\\textit{Month Year -- Present} \\hfill \\textit{City, Country}',
      '\\begin{itemize}[leftmargin=*]',
      '  \\item Describe a key responsibility or achievement.',
      '  \\item Quantify impact where possible.',
      '\\end{itemize}',
      '',
      '\\section{Education}',
      '\\textbf{Degree, Field of Study} \\hfill University Name \\\\',
      '\\textit{Month Year -- Month Year} \\hfill \\textit{City, Country}',
      '',
      '\\section{Skills}',
      'List relevant skills, tools, and languages here.',
      '',
      '\\end{document}',
      '',
    ].join('\n'),
  },
  {
    id: 'cover-letter',
    name: 'Cover Letter',
    description: 'Formal letter with sender/recipient blocks, ready to fill in.',
    category: 'personal',
    previewImage: '/templates/cover-letter.png',
    mainTexContent: [
      '\\documentclass{letter}',
      '\\usepackage[utf8]{inputenc}',
      '\\signature{Your Name}',
      '\\address{Your Name \\\\ Your Address \\\\ City, Country}',
      '',
      '\\begin{document}',
      '',
      '\\begin{letter}{Hiring Manager \\\\ Company Name \\\\ Company Address}',
      '',
      '\\opening{Dear Hiring Manager,}',
      '',
      'I am writing to express my interest in the position at your company.',
      'Explain briefly why you are a strong fit here.',
      '',
      '\\closing{Sincerely,}',
      '',
      '\\end{letter}',
      '',
      '\\end{document}',
      '',
    ].join('\n'),
  },
  {
    id: 'beamer-presentation',
    name: 'Presentation Slides',
    description: 'Beamer slide deck with a title slide and a few starter frames.',
    category: 'presentation',
    previewImage: '/templates/beamer-presentation.png',
    mainTexContent: [
      '\\documentclass{beamer}',
      '\\usetheme{Madrid}',
      '',
      '\\title{Presentation Title}',
      '\\author{Your Name}',
      '\\date{\\today}',
      '',
      '\\begin{document}',
      '',
      '\\frame{\\titlepage}',
      '',
      '\\begin{frame}{Outline}',
      '  \\tableofcontents',
      '\\end{frame}',
      '',
      '\\section{Introduction}',
      '\\begin{frame}{Introduction}',
      '  \\begin{itemize}',
      '    \\item First point',
      '    \\item Second point',
      '  \\end{itemize}',
      '\\end{frame}',
      '',
      '\\section{Conclusion}',
      '\\begin{frame}{Conclusion}',
      '  Summarize your key takeaways here.',
      '\\end{frame}',
      '',
      '\\end{document}',
      '',
    ].join('\n'),
  },
]
